### ISSUE TITLE
git lfs fetch with reference repo should not copy objects

### ISSUE THREAD

**Issue by arikon** [github/git-lfs#1391] opened 2016-07-22 11:51 UTC
`git lfs clone` / `fetch` with configured reference repository (see `LocalReferenceDir` below) copies lfs objects from reference repository to the current repository. But should not, as `git clone` / `fetch` does not either. `lfs` objects should be used directly from the reference repository.

This should increase `git lfs checkout` speed a bit and save a lot of HDD space ;)

```
git-lfs/1.2.1 (GitHub; darwin amd64; go 1.6.2)
git version 2.9.0

Endpoint=https://github.yandex-team.ru/serp/web4.git/info/lfs (auth=none)
  SSH=git@github.yandex-team.ru:serp/web4.git
LocalWorkingDir=/Users/arikon/projects/sandbox/tmp
LocalGitDir=/Users/arikon/projects/sandbox/tmp/.git
LocalGitStorageDir=/Users/arikon/projects/sandbox/tmp/.git
LocalMediaDir=/Users/arikon/projects/sandbox/tmp/.git/lfs/objects
LocalReferenceDir=/Users/arikon/.cache/serp-ci/github.yandex-team.ru/serp/web4.git/lfs/objects
TempDir=/Users/arikon/projects/sandbox/tmp/.git/lfs/tmp
ConcurrentTransfers=15
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Comment by technoweenie** [comment] 2016-07-25 15:15
This would be interesting. Any thoughts on how it'd work? Of course it'd have to work cross platform, and with the clean/smudge filters.

**Comment by sinbad** [comment] 2016-08-03 13:58
It actually doesn't copy the files. They look like they're there, but they're actually a hard link. So they're not actually taking up any space at all *waves magic hands*

Hard linking is done because then you can delete *either folder* and it'll keep working. If it was just a symlink or an in-code reference, then deleting the referenced dir would break the referencing repo. It doesn't with hard links.

So I don't think this is a bug.

**Comment by sinbad** [comment] 2016-08-03 13:59
> It actually doesn't copy the files

Caveat: provided the file system supports hard links. That should be true on any decent file system these days, including NTFS on Windows. It will fall back on a regular copy if hard links aren't supported, e.g. FAT32 but *oh god why would you ever do that*

**Comment by arikon** [comment] 2016-08-03 19:45
@sinbad Reference and working repos could be located on the separate volumes. Hard links work only inside a single volume.

**Comment by sinbad** [comment] 2016-08-04 10:12
Then IMO you live with the duplication.

**Comment by sschaetz** [comment] 2016-08-04 15:50
I'm trying to get this working (deduplication of git-lfs tracked files) but I'm struggling:

```
$ sw_vers -productVersion
10.11.5
$ git version
git version 2.9.0
$ git lfs version
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)
```

I do:
```
cd ~
mkdir scratch
cd scratch
mkdir cache
cd cache
git clone git@github.com:user/repo.git
cd ..
git clone git@github.com:user/repo.git repo --reference ~/scratch/cache/repo/
cd ..
git clone git@github.com:user/repo.git repo2 --reference ~/scratch/cache/repo/
```
But I don't see git lfs files as hard-links in `repo` or `repo2` and they are downloaded every time.

**Comment by sinbad** [comment] 2016-08-04 16:13
@sschaetz you have the arguments in the wrong place, it should be:
```
git clone --reference ~/scratch/cache/repo/ git@github.com:user/repo.git repo2 
```
I just did this here with a sizeable repo and it took no time at all and didn't download any LFS files.
You can tell they're hardlinks by looking at the reference count in `ls -l`, or explicitly look at the inode in `ls -li`, like so:

```sh
> ls -li .git/lfs/objects/8f/b8
95215789 -rw-r--r--  2 steve  staff  58709919  4 Aug 17:02 8fb8c920829f3b086680e2894a35cd94093962de2b49d32b167e967b5b1771d0 
> ls -li ../reference-repo/.git/lfs/objects/8f/b8
95215789 -rw-r--r--  2 steve  staff  58709919  4 Aug 17:02 8fb8c920829f3b086680e2894a35cd94093962de2b49d32b167e967b5b1771d0 
```
Notice how the first number, the inode `95215789`, is exactly the same (as is the modified date even though I cloned the one in the current dir later), and the number just after the permissions is `2`, which indicates this is one of 2 hardlinks pointing to this inode.

**Comment by sschaetz** [comment] 2016-08-04 23:44
Thanks a lot! I did it wrong, I can reproduce your results now.

I think next to wrong command line my error here was that I thought this would do more. I was hoping I could save even more memory by having the git-lfs files themselves as hardlinks, they still seem to be copied. I guess there is no way around that.

**Comment by sinbad** [comment] 2016-08-05 13:31
Oh you mean in the working copy? Yeah those can't be hard links, otherwise editing the files would also change their contents in the object store, changing their state for previous commits. If git was like older systems when you had to 'check out' a file before editing then it might be possible, but it's more laisse-faire (rightly IMO, check out before editing was a PITA).

**Comment by arikon** [comment] 2016-08-05 18:21
> Then IMO you live with the duplication.

@sinbad So, the ticket is about fixing that ;)

**Comment by sinbad** [comment] 2016-08-08 11:48
>  So, the ticket is about fixing that ;)

Sorry, I'm saying it's the correct behaviour. Doing what you suggest is equivalent to the `--shared` option in `git clone`, which specifically warns about how this can result in data loss if objects in the other repo are deleted.

**Comment by technoweenie** [comment] 2016-08-18 15:56
Closing this, I agree with @sinbad and don't see us changing this.

**Closed by technoweenie** 2016-08-18 15:56 UTC
Labels: enhancement

**Comment by rockbruno** [comment] 2025-02-22 11:29
Is it intentional that this functionality doesn't work with `--dissociate`? Cloning with `--reference` and then manually cleaning the alternates seem to work, but cloning with the `--dissociate` flag specifically results in LFS files being downloaded even though under the hood it shouldn't be doing anything different from the manual steps.
