### ISSUE TITLE
Git push tries to upload large files that are already cached

### ISSUE THREAD

**Issue by bagratkirakosian** [github/git-lfs#1529] opened 2016-09-20 10:48 UTC
Whenever we added large files to our repo and then others pull it (git lfs pull), lfs doesnt recognize those large files (git lfs ls-files) and tries to push them every time but whenever we make a new clone AFTER large files were added to repo it works correctly. 

Issue only occurs when local copy wasn't with lfs and then it became with lfs after pull.

**Comment by ttaylorr** [comment] 2016-09-20 15:10
Hi @bagratkirakosian, thanks for opening this. Is LFS installed on the machines you're using to pull with? The important step is to run `git lfs setup` to make sure.

**Comment by bagratkirakosian** [comment] 2016-09-20 15:28
Hi @ttaylorr thanks for a quick reply! Yes `git lfs install` `git lfs pull` has been done but it didn't solve the problem because `git lfs ls-files` gives empty list of tracked files but in .gitattributes they are specified.

**Comment by ttaylorr** [comment] 2016-09-20 16:41
@bagratkirakosian OK, good to rule that out. Is your repository public? I'd love to try and pull it myself to see if I can reproduce this and perhaps rule out some more possible problems.

**Comment by bagratkirakosian** [comment] 2016-09-20 17:21
@ttaylorr nope we are using private version of github and the repo is private too. But even if it was public you won't be able to reproduce because clean clone works. Issue appears when old clones pull new changes where large files appeared. Let me know if I can provide any other helpful information.

**Comment by ttaylorr** [comment] 2016-09-20 17:25
@bagratkirakosian It's unclear to me what the issue is here. Is the issue that pulls between LFS changes _pushes_ those changes back to the server? If you could provide some numbered steps to reproduce, I should be able to help you out more.

**Comment by bagratkirakosian** [comment] 2016-09-20 17:45
Ok here are steps that will help you:
1. We had a normal repository (Not LFS).
2. Everyone else in the organization had clone of that repo and some other branches from `master`.
3. Then people who have write access to `master` pushed some large files with LFS.
4. Everyone was told to commit old changes because we are migrating to LFS.
5. Everyone else installed LFS using brew mostly and pulled new changes including large files.
6. We had 3 large files and in different computers different files from those 3 were marked as modified. We did `git reset --hard` and `git checkout .` but those files kept getting marked modified always but sometimes we were able to discard them and push failed because git tried to upload those files. This was the most strange step.
7. Result: People can't push anymore because git doesn't recognize LFS files and tries to push them but as far as it is a normal push git server rejects all files that are larger than 100 mb.
8. Some people who didn't have commits made a fresh new clone of repo and it works fine but others who have lot's of commits want to push changes but they can't do it.

Does this help now? :) Thanks for quick replies all the time.

**Comment by ttaylorr** [comment] 2016-09-20 18:04
@bagratkirakosian Thanks for the info. I think there are two problems going on here:

> We did `git reset --hard` and `git checkout` . but those files kept getting marked modified

I believe this is the same issue as https://github.com/github/git-lfs/issues/1339. I'd have to know more about your directory structure to be certain, but my hunch is after running BFG (see below) and making sure your `.gitattributes` are set-up correctly as described in that issue, this should be resolved.

> People can't push anymore because git doesn't recognize LFS files

Your old objects are not being tracked by LFS. Even though there are patterns that cover those files in your `.gitattributes`, the order in which those two steps happen is important. You'll need to convert the repo to LFS by using a tool. I recommend: https://rtyley.github.io/bfg-repo-cleaner/.

**Comment by ttaylorr** [comment] 2016-10-12 17:35
Going to close this one out for now, since things are pretty quiet in this issue. If the issue comes back up again, please don't hesitate to re-open this!

**Closed by ttaylorr** 2016-10-12 17:35 UTC
