### ISSUE TITLE
git push fails to push commit to Github when connection to Github times out using third-party git-lfs server

### ISSUE THREAD

**Issue by pfalcone-itrs** [github/git-lfs#1498] opened 2016-09-01 13:50 UTC
Git LFS server used here is a third-party implementation (Artifactory). 

We encounter a failure to push commits on this scenario: 
1. We are attempting to push a big file (around 500MB+) that takes a long time to upload to the Git LFS server (as I'm attempting to perform the operation from Manila, PH where internet connectivity is not that good).
2. The connection to Github times out during git push
3. The binary transfer seems to continue but the commit being pushed to github.com is not replicated there.

Earlier, I tried to perform git lfs push first as that just uploads the binary object to the git-lfs server. Thinking that once the git lfs push finishes I can push the git commit separately to Github (as I was thinking without the git-lfs push to worry about there won't be a timeout operation to github.com this time around) I then performed a git push. Unfortunately git-lfs push was reattempted by the git client, resulting again in this scenario.

Actual repository and git-lfs server URL used is changed in this log trace

```
GIT_TRACE=1 git push origin master
19:34:46.042047 git.c:344               trace: built-in: git 'push' 'origin' 'master'
19:34:46.044925 run-command.c:334       trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '\''sample/resources.git'\'''
19:34:49.289295 run-command.c:334       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@github.com:sample/resources.git'
19:34:49.300251 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@github.com:sample/resources.git'
19:34:49.303119 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github.com:sample/resources.git'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: git rev-list --objects --stdin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l -f /Users/myuser/resources/.lfsconfig
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 1
trace git-lfs: api: batch 1 files
trace git-lfs: Filled credentials for https://artifactory.sample.com/artifactory/api/lfs/blob-lfs
trace git-lfs: HTTP: POST https://artifactory.sample.com/artifactory/api/lfs/blob-lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {
  "objects" : [ {
    "oid" : "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88",
    "size" : 531734475,
    "_links" : {
      "upload" : {
        "href" : "https://artifactory.sample.com/blob-lfs/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88;sha256=007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88",
        "header" : {
          "Authorization" : "Basic cGZhbGNvbmVAaXRyc2dyb3VwLmNvbTpBUEpFZTE3Y3FLSmo4QmpxZnJRVFBXR
trace git-lfs: HTTP: 0h2cg=="
        }
      }
    }
  } ]
}
trace git-lfs: HTTP:
trace git-lfs: tq: starting transfer adapter "basic"
Git LFS: (0 of 1 files) 0 B / 507.10 MB                                        trace git-lfs: xfer: adapter "basic" Begin() with 3 workers
trace git-lfs: xfer: adapter "basic" started
trace git-lfs: xfer: adapter "basic" Add() for "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
trace git-lfs: xfer: adapter "basic" worker 2 starting
trace git-lfs: xfer: adapter "basic" worker 0 starting
trace git-lfs: xfer: adapter "basic" worker 2 waiting for Auth
trace git-lfs: xfer: adapter "basic" worker 0 processing job for "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
trace git-lfs: xfer: adapter "basic" worker 1 starting
trace git-lfs: xfer: adapter "basic" worker 1 waiting for Auth
trace git-lfs: HTTP: PUT https://artifactory.sample.com/artifactory/blob-lfs/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88;sha256=007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88
trace git-lfs: xfer: adapter "basic" worker 2 auth signal received
trace git-lfs: xfer: adapter "basic" worker 1 auth signal received
Git LFS: (0 of 1 files) 214.73 MB / 507.10 MB                                  Connection to github.com closed by remote host.
Git LFS: (0 of 1 files) 496.34 MB / 507.10 MB                                  trace git-lfs: HTTP: 504
trace git-lfs: xfer: adapter "basic" worker 0 finished job for "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
trace git-lfs: tq: retrying object 007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88
trace git-lfs: tq: retrying 1 failed transfers
trace git-lfs: tq: sending batch of size 1
trace git-lfs: api: batch 1 files
trace git-lfs: Filled credentials for https://artifactory.sample.com/artifactory/api/lfs/blob-lfs
trace git-lfs: HTTP: POST https://artifactory.sample.com/artifactory/api/lfs/blob-lfs/objects/batch
Git LFS: (0 of 1 files) 496.34 MB / 507.10 MB                                  trace git-lfs: HTTP: 200
Git LFS: (0 of 1 files) 496.34 MB / 507.10 MB                                  trace git-lfs: HTTP: {
  "objects" : [ {
    "oid" : "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88",
    "size" : 531734475,
    "_links" : {
      "upload" : {
        "href" : "https://artifactory.sample.com/artifactory/blob-lfs/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88;sha256=007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88",
        "header" : {
          "Authorization" : "Basic cGZhbGNvbmVAaXRyc2dyb3VwLmNvbTpBUEpFZTE3Y3FLSmo4QmpxZnJRVFBXR
trace git-lfs: HTTP: 0h2cg=="
        }
      }
    }
  } ]
}
Git LFS: (0 of 1 files) 496.34 MB / 507.10 MB                                  trace git-lfs: HTTP:
trace git-lfs: xfer: adapter "basic" End()
trace git-lfs: xfer: adapter "basic" worker 2 stopping
trace git-lfs: xfer: adapter "basic" worker 0 stopping
trace git-lfs: xfer: adapter "basic" worker 1 stopping
trace git-lfs: xfer: adapter "basic" stopped
trace git-lfs: tq: starting transfer adapter "basic"
trace git-lfs: xfer: adapter "basic" Begin() with 3 workers
trace git-lfs: xfer: adapter "basic" started
trace git-lfs: xfer: adapter "basic" Add() for "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
trace git-lfs: xfer: adapter "basic" worker 1 starting
trace git-lfs: xfer: adapter "basic" worker 0 starting
trace git-lfs: xfer: adapter "basic" worker 0 processing job for "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
trace git-lfs: xfer: adapter "basic" worker 1 waiting for Auth
trace git-lfs: xfer: adapter "basic" worker 2 starting
trace git-lfs: xfer: adapter "basic" worker 2 waiting for Auth
trace git-lfs: HTTP: PUT https://artifactory.sample.com/artifactory/blob-lfs/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88;sha256=007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88
trace git-lfs: xfer: adapter "basic" worker 1 auth signal received
trace git-lfs: xfer: adapter "basic" worker 2 auth signal received
Git LFS: (0 of 1 files) 1003.44 MB / 507.10 MB                                 trace git-lfs: HTTP: 201
trace git-lfs: HTTP: {
  "repo" : "blob-lfs",
  "path" : "/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88",
  "created" : "2016-08-30T15:38:48.550Z",
  "createdBy" : "sampleuser@sample.com",
  "downloadUri" : "https://artifactory.sample.com/artifactory/blob-lfs/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88",
  "mimeType" : "application/octet-stream",
  "size" : "531734475",
  "checksums" : {
    "sha1" : "bbb606ad878105eb6095ee1a1455280e80219e89",
    "md5" : "6e852d35e11cf3c4d210490398de7c92"
  },
  "originalChecksums" : {
  },
  "uri" : "https://artifactory.sample.com/artifactory/blob-lfs/objects/00/7c/007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
}
trace git-lfs: xfer: adapter "basic" worker 0 finished job for "007cb9316869e1f46f51add103eb6cc7158d0d14205bf52fced4af425b843d88"
trace git-lfs: xfer: adapter "basic" End()
trace git-lfs: xfer: adapter "basic" worker 1 stopping
trace git-lfs: xfer: adapter "basic" worker 0 stopping
trace git-lfs: xfer: adapter "basic" worker 2 stopping
trace git-lfs: xfer: adapter "basic" stopped
Git LFS: (1 of 1 files) 1003.44 MB / 507.10 MB
```

**Comment by technoweenie** [comment] 2016-09-02 17:33
Hi @pfalcone-itrs :wave:  Git LFS halts a git push if the LFS objects fail to upload. If Git LFS allowed the push to the git host even though the push to the lfs host failed, then you'd end up with an incomplete repository with missing LFS objects. We could add a flag to allow git pushes after failed lfs uploads, but I'm not really sure why someone would want that.

Running `git lfs push` before a `git push` _should_ only upload objects once, but only if Git LFS is scanning the same range of commits for both operations. Unfortunately, this isn't easy to get from `GIT_TRACE=1` output:

```
$ GIT_TRACE=1 git lfs push origin master
10:48:50.053749 git.c:563               trace: exec: 'git-lfs' 'push' 'origin' 'master'
10:48:50.054249 run-command.c:336       trace: run_command: 'git-lfs' 'push' 'origin' 'master'
trace git-lfs: run_command: 'git' version
trace git-lfs: Upload refs [master] to remote origin
trace git-lfs: run_command: git rev-list --objects master --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 0
```

Based on that, you can see that it's looking for LFS objects in your `master` branch that have not been pushed to the `origin` remote.

    git rev-list --objects master --not --remotes=origin --

Your output shows a little less info:

```
19:34:49.303119 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github.com:sample/resources.git'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: git rev-list --objects --stdin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
```

The `git lfs pre-push` gets the exact range of commits that it's going to upload to your remote. It then scans those commits for LFS objects to upload. Unfortunately, our tracing doesn't report the exact commits. We can look into making these trace messages more useful.

**Comment by pfalcone-itrs** [comment] 2016-09-03 14:03
Running git lfs push before a git push only uploading objects once is the behavior I am expecting if the uploading operation is long enough to make github.com close the connection. Pushing to github.com should normally just transmit the commit and the pointer (since it has already been uploaded before).

**Comment by ttaylorr** [comment] 2016-09-05 18:01
@pfalcone-itrs: thanks for following up! 😄 

This behavior is supported in Git LFS as I understand it. If you already have pushed LFS objects up to your remote by means of a `git lfs push`, the subsequent `git push` will skip those previously uploaded objects.

The steps I took to reproduce this were:

0. Initialize a new repository
0. Preform a `git lfs track`.
0. Committed and pushed my `.gitattributes` file.
0. Inserted contents into a LFS-tracked file, "a.dat"
0. Committed that file locally.
0. Pushed the new LFS objects (via `git lfs push`)
0. Did a normal Git push (`git push`) and LFS skipped the previously-pushed objects.

```
~/d/g/lfs-test (master) $ g lfs push origin master
Git LFS: (1 of 1 files) 8 B / 8 B                                                                                                             

~/d/g/lfs-test (master) $ git push
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 8 B skipped                                                                                     Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 396 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git@github.com:ttaylorr/lfs-test.git
   57489d8..43b5863  master -> master
```

**Comment by ttaylorr** [comment] 2016-10-12 17:39
Hi @pfalcone-itrs, I'm going to close this one out for now, since things are pretty quiet in this issue. If you have any further questions, please don't hesitate to re-open this!

**Closed by ttaylorr** 2016-10-12 17:39 UTC
