### ISSUE TITLE
Git lfs not sending files

### ISSUE THREAD

**Issue by iwootten** [github/git-lfs#395] opened 2015-06-15 18:14 UTC
In trying to use lfs, I'm finding none of my files are sent. I've followed through installing lfs and see that git lfs track shows the files are being tracked. 

However, when I push back to the repo in question (https://github.com/iwootten/dragontest), none of the files are sent, just the sha info files.

I also attempted "git lfs push origin master" but get 

    (0 of 0 files) 0 B 0

**Comment by technoweenie** [comment] 2015-06-16 17:36
It looks like there are no Git LFS objects to send. Have you done the following?

1. Use `git lfs track` to specify file types and/or directories of files to store in Git LFS.
2. Committed new or modified files that match the tracked file type or directory.
3. Push the new commits to your Git server.

**Comment by iwootten** [comment] 2015-06-17 08:29
Yup. As I mentioned,  git lfs track shows the files are being tracked.

**Comment by technoweenie** [comment] 2015-06-17 16:19
Use `git lfs ls-files` to see what files in the current working directory actually _use_ Git LFS.  The `track` command just tells `git add` to store files through Git LFS from that point on. It doesn't retroactively update existing commits.

**Comment by iwootten** [comment] 2015-06-17 21:43
Ok, I'm given a list of the same files when using `git lfs ls-files`, which are all those listed in that current repo.

**Comment by technoweenie** [comment] 2015-06-17 21:52
Mind if I invite the email on your public gh profile to our slack channel? I should be able to help you out there. It doesn't look like you're hitting a bug... but it's difficult to troubleshoot without details.

**Comment by iwootten** [comment] 2015-06-17 22:09
No probs

**Comment by ndrego** [comment] 2015-06-17 22:51
I am having the exact same issue here. Can any resolution be posted back here?

**Comment by technoweenie** [comment] 2015-06-17 22:55
Turns out your Git version is so old it doesn't support pre push hooks. Therefore it's not uploading your Git LFS objects _before_ uploading the Git objects.  That's also why running `git lfs push origin master` doesn't send anything after all the Git objects have been pushed. It compares the local repo's HEAD commit to the one on the remote Git server and assumes there's nothing left to be done.

You can force Git LFS to upload EVERY object referenced for a branch like this:

1. Ensure you're on the correct branch, with no changes to commit (`git status`)
2. Get the latest commit with `git log -n 1`
3. Run the pre-push hook manually:

        echo “refs/heads/master {commit}  refs/heads/master 0000000000000000000000000000000000000000” | GIT_TRACE=1 git lfs pre-push origin

Note: The `GIT_TRACE=1` is not necessary for normal operation. But if you have problems, dump that trace output in a Gist and reference it here.

Opened #410 with a description so we can fix this.

@ndrego: What version of Git are you using?

**Comment by ndrego** [comment] 2015-06-17 23:00
We are using 1.7.1 here.

**Comment by technoweenie** [comment] 2015-06-17 23:02
Ah, you'll want 1.8.2+. I believe 1.8.x introduced git credential helpers for smart https pushing. [1.8.2 introduce the `pre-push` hook](http://blog.ittybittyapps.com/blog/2013/09/03/git-pre-push/).

**Comment by ndrego** [comment] 2015-06-17 23:24
@technoweenie Just installed 2.4.4 from source and I'm getting the same behavior:

```[nigel@rum test_large_files]$ git push origin master
Everything up-to-date
[nigel@rum test_large_files]$ git lfs push origin master
(0 of 0 files) 0 B 0```

**Comment by michael-k** [comment] 2015-06-18 01:34
@ndrego:
> It compares the local repo's HEAD commit to the one on the remote Git server and assumes there's nothing left to be done.

That's true for git 2.x too. So your push doesn't help:
```
$ git push origin master
Everything up-to-date
```
=> Try to push to another repo or move the branch master on origin back to a pre-lfs commit and push again:
```
git push -f origin <commit>:master
git push origin master
```

**Comment by ndrego** [comment] 2015-06-18 04:44
Got it, that got me further along, but still no dice:

```
[nigel@rum test_large_files]$ git push -u origin master
Error uploading file test.blah (18e94b47a162dbdbc820a20f8801aeabada9f9884288007d079876418c19110f)

Errors logged to /tmp/nigel/test_large_files/.git/lfs/objects/logs/20150617T214211.800926183.log.
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'git@github.internal:nigel/test_large_files.git'
[nigel@rum test_large_files]$ git lfs logs last
> git-lfs pre-push origin git@github.internal:nigel/test_large_files.git
LocalWorkingDir=/tmp/nigel/test_large_files
LocalGitDir=/tmp/nigel/test_large_files/.git
LocalMediaDir=/tmp/nigel/test_large_files/.git/lfs/objects
TempDir=/tmp/nigel/test_large_files/.git/lfs/tmp
GIT_PREFIX=

Error uploading file test.blah (18e94b47a162dbdbc820a20f8801aeabada9f9884288007d079876418c19110f)

Cannot clean a Git LFS pointer.  Skipping.
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/commands.logPanic(0x7fa1a71beb40, 0xc208045900, 0x7fa1a701ea00, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:156 +0xf17
github.com/github/git-lfs/commands.handlePanic(0x7fa1a71beb40, 0xc208045900, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:108 +0x6c
github.com/github/git-lfs/commands.LoggedError(0x7fa1a71beb40, 0xc208045900, 0xc20802c000, 0x61, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:65 +0x89
github.com/github/git-lfs/commands.Panic(0x7fa1a71beb40, 0xc208045900, 0xc20802c000, 0x61, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:75 +0x68
github.com/github/git-lfs/commands.prePushCommand(0x98d880, 0xc208044d80, 0x2, 0x2)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands_pre_push.go:84 +0x775
github.com/spf13/cobra.(*Command).execute(0x98d880, 0xc208044d60, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x98d780, 0xc20800e010, 0x3, 0x3, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x98d780, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
	/Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

**Comment by technoweenie** [comment] 2015-06-18 13:17
@ndrego: The `git lfs push` command works similarly to `git push`: it compares the current branch to the one on the remote, and only pushes the necessary commits. Since your git remote is current with your local branch, there are no commits to push, and therefore no Git LFS objects to push.  See the steps in [my comment](https://github.com/github/git-lfs/issues/395#issuecomment-112974707) to force it to push everything referenced in the branch.

That second error is because your "test.blah" file is a git lfs pointer in the git working directory. Something like this:

    version https://git-lfs.github.com/spec/v1
    oid sha256:4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393
    size 12345

It's because your repository is in a weird state from being created using the wrong Git version. Can you push the repository to GitHub.com so I can look at it? Judging by the name in the stack trace, it's nothing private. Having the actual repo will help us track down and fix the bug, so it's not such a show stopper. I can create an empty private repo for you to push it to if you want to keep it between us.

Considering that it IS a test repo, I'd recommend trying to create a new repo with the new Git version.

**Comment by ndrego** [comment] 2015-06-18 16:49
Created a fresh repo locally and on GH Enterprise. First push attempt after doing git lfs tracking was stymied by `x509: certificate signed by unknown authority` for which I used ```git config http.sslverify false``` (as specified in https://github.com/github/git-lfs/issues/276). Subsequent push attempt resulted in 

```
[nigel@rum tlf]$ git config http.sslverify false
[nigel@rum tlf]$ git push origin master
(0 of 1 files) 0 B / 100.00 MB  0.00 %                                                                                                                                                                    Username for 'https://github.internal': nigel
Password for 'https://nigel@github.internal': 
(1 of 1 files) 0 B / 100.00 MB  0.00 % 5s                                                                                                                                                                 
Not Found
Docs: https://help.github.com/enterprise
error: failed to push some refs to 'git@github.internal:nigel/tlf.git'
```

I tried re-creating the repo again and doing the `git config http.sslverify false` prior to any push attempt, but this resulted in the same error.

I then tried to push the repo to my personal github.com account and got:

```
[nigel@rum tlf]$ git remote add gh git@github.com:ndrego/tlf.git
[nigel@rum tlf]$ git push gh master
(1 of 1 files) 0 B / 100.00 MB  0.00 % 1s                                                                                                                                                                 
You're signed up for early access and invitations will be going out soon. We're excited about Git LFS too!
Docs: https://github.com/contact
error: failed to push some refs to 'git@github.com:ndrego/tlf.git'
```

As for git version:
```
[nigel@rum tlf]$ git --version
git version 2.4.4
```

**Comment by technoweenie** [comment] 2015-06-18 16:54
@ndrego: It looks like you don't have Git LFS enabled on your Enterprise instance or GitHub.com. The tool is still in early access.

* For Enterprise, get your admin [to enable Git LFS](https://help.github.com/enterprise/2.2/admin/articles/configuring-git-large-file-storage-for-a-repository/). It's possible to enable it for an individual repo, a user or org, or the entire instance.
* For GitHub.com, I'll see if I can get you Early Access since it looks like you're signed up.

I'm closing this issue because the original bug has been defined. If you have specific questions about GitHub setup, go through support@github.com.

**Closed by technoweenie** 2015-06-18 16:54 UTC

**Comment by ahmadawais** [comment] 2016-07-13 07:36
@technoweenie "For GitHub.com, I'll see if I can get you Early Access" how can I get in? Any help?

**Comment by technoweenie** [comment] 2016-07-13 11:49
@ahmadawais Git LFS has shipped to all users, so there's no early access program for it anymore :)

**Comment by ahmadawais** [comment] 2016-07-13 12:11
@technoweenie But I am facing the same problem, I tried uploading it and not sure if it was uploaded. How can I confirm?

**Comment by technoweenie** [comment] 2016-07-13 12:16
Please open a new issue with details, so we can help you out. Continuing to comment here notifies the old participants on a year old closed issue. Thanks!

**Comment by lieff** [comment] 2018-08-17 09:32
I have same issue. `git lfs ls-files` shows migrated files fine in local https://github.com/lieff/minimp3 repo. But files can`t be pushed to github.
I tried force method above with no luck:
```
$ echo “refs/heads/master 1aee2bea17e83029a5b68a9dc5e1b608422f7175  refs/heads/master 0000000000000000000000000000000000000000” | GIT_TRACE=1 git lfs pre-push origin
12:27:33.715894 git.c:576               trace: exec: git-lfs pre-push origin
12:27:33.715916 run-command.c:640       trace: run_command: git-lfs pre-push origin
12:27:33.717676 trace git-lfs: exec: git 'version'
12:27:33.720088 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=''-c' 'filter.lfs.required=false' 'rev-parse' 'HE
AD' '--symbolic-full-name' 'HEAD'
12:27:33.722753 trace git-lfs: exec: git 'config' '-l'
12:27:33.726134 trace git-lfs: pre-push: “refs/heads/master 1aee2bea17e83029a5b68a9dc5e1b608422f7175 refs/heads/master 0000000000000000000000000000000000000000”
12:27:34.342019 trace git-lfs: creds: git credential fill ("https", "github.com", "")
Username for 'https://github.com': lieff
Password for 'https://lieff@github.com':
12:27:39.157153 trace git-lfs: Filled credentials for https://github.com/lieff/minimp3
12:27:39.157289 trace git-lfs: HTTP: POST https://github.com/lieff/minimp3.git/info/lfs/locks/verify
12:27:39.739771 trace git-lfs: HTTP: 200
12:27:39.739822 trace git-lfs: creds: git credential approve ("https", "github.com", "")
12:27:39.743847 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

12:27:39.743989 trace git-lfs: tq: running as batched queue, batch size of 100
12:27:39.744255 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
12:27:39.745633 trace git-lfs: run_command: git cat-file --batch
12:27:39.746564 trace git-lfs: tq: sending batch of size 0
12:27:39.746581 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
12:27:39.746588 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
12:27:39.746602 trace git-lfs: filepathfilter: rejecting "tmp" via []
12:27:39.746607 trace git-lfs: filepathfilter: accepting "tmp"
12:27:39.746637 trace git-lfs: filepathfilter: rejecting "objects" via []
12:27:39.746641 trace git-lfs: filepathfilter: accepting "objects"
```

**Comment by ttaylorr** [comment] 2018-08-20 15:27
> I have same issue.

Sorry to hear that. Can you please open a new issue instead of
commenting on a closed one? It would be helpful to include relevant
details and a set of steps to reproduce the issue so that we can be more
helpful in running this down.

Thanks!
