### ISSUE TITLE
Weird config clash warning after intialising LFS

### ISSUE THREAD

**Issue by KingScooty** [github/git-lfs#908] opened 2015-12-21 20:35 UTC
I've just initialised LFS to track *.png and *.jpg images for the project i'm working on. The first error i got was this:

```sh
$ git lfs track "*.jpg"
*.jpg is outside repository
```

The `.gitattributes` file is created, but empty.
I do have 2 symlinks in my project, but to folders unrelated to where the images are stored.

When i tried to commit and push to github after doing this, i got the following error that wouldn't go away until i deleted my repo and re-cloned it from github:

```sh
WARNING: These git config values clash:
  git config "url.git@github.com:.pushinsteadof" = "github:"
  git config "url.git@github.com:.pushinsteadof" = "git://github.com/"
WARNING: These git config values clash:
  git config "url.git@gist.github.com:.pushinsteadof" = "gist:"
  git config "url.git@gist.github.com:.pushinsteadof" = "git://gist.github.com/"
Counting objects: 2, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 230 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
```

**Comment by technoweenie** [comment] 2015-12-24 23:00
Fixed via #861, but wasn't deemed important enough for its own patch release right before the holidays.

**Comment by kankaristo** [comment] 2016-01-31 21:45
@technoweenie, is there a timeline for the release containing this fix?

I'm holding back from starting to use LFS at our company because of the noise from the warnings.

**Comment by technoweenie** [comment] 2016-02-05 23:37
It's out now: https://github.com/github/git-lfs/releases/tag/v1.1.1

Apologies for the delay, I had a big backlog to catch up on :)

**Closed by technoweenie** 2016-02-05 23:37 UTC

**Comment by rc1** [comment] 2016-02-17 09:30
Getting these warnings after installing `git-lfs 1.1.0` via homebrew. This was the first install of git-lfs on my system. Much appreciated if you can advise how to fix manually (which value should I keep?)

**Comment by andrey-yantsen** [comment] 2016-02-17 09:36
@rc1 update your homebrew cache and install `git-lfs 1.1.1`

**Comment by rc1** [comment] 2016-02-17 09:38
Sorry... early morning. Thank you.

**Comment by mramato** [comment] 2016-02-19 14:20
I just installed 1.1.1 on Windows and am still having this problem.  Do I have to perform any sort of re-initialization after upgrading?

**Comment by mramato** [comment] 2016-02-23 01:52
For anyone else that ran into this problem, here's how to fix it:

It turns out that installing git-lfs 1.1.1 on a Windows machine that already has 1.1.0 does not work.  Installing 1.1.0 sticks `git-lfs.exe` in `Program Files\Git\mingw64\bin` and `Program Files\Git\cmd`.  Installing 1.1.1 does not remove these versions so Git continues to see these binaries instead of 1.1.0.  You have to go into the `Program Files\Git\mingw64\bin` and run the git-lfs-uninstaller located there manually.

**Comment by bazooka241** [comment] 2016-02-23 16:23
お忙しいところ失礼いたします。
先日は私の身勝手な行動で不快な思いをさせてしまいまして申し訳ございませんでした、
２度とこのようなことが起きないように努力します。
本当に申し訳ございませんでした１から勉強させてください。

**Comment by bazooka241** [comment] 2016-02-23 16:23
You will excuse me busy place.
The other day was sorry I have to unpleasant feelings in my selfish behavior,
And twice we will try to not to cause such a thing.
Please let me study from 1 did not Thank really sorry.

**Comment by MStroughair** [comment] 2016-03-21 02:23
Hi there,

I'm getting these errors just after installation of Git lfs for the first time. I'm willing to ignore them however, are they something that I need to worry about?

**Comment by mramato** [comment] 2016-03-23 02:58
@MStroughair It depends on what the exact errors you are getting.  Also, if you are running git-lfs 1.1.1 or newer you should not be seeing them.

**Comment by jhessin** [comment] 2016-04-14 06:06
So I just installed git-lfs through Chocolatey and it (Chocolatey) says I have v1.1.2. However if I run git-lfs from the command line it looks like I have v1.1.0. When trying to push files I get the following error:
***
 git push
WARNING: These git config values clash:
  git config "http.sslcainfo" = "C:/Program Files/Git/mingw64/ssl/certs/ca-bundl                                                                                                                                                    e.crt"
  git config "http.sslcainfo" = "/ssl/certs/ca-bundle-ghfw.crt"
WARNING: These git config values clash:
  git config "core.editor" = "gitpad"
  git config "core.editor" = "'C:/Program Files (x86)/Notepad++/notepad++.exe' -                                                                                                                                                    multiInst -notabbar -nosession -noPlugin"
WARNING: These git config values clash:
  git config "diff.tool" = "vs2013"
  git config "diff.tool" = "vsdiffmerge"
WARNING: These git config values clash:
  git config "difftool.prompt" = "false"
  git config "difftool.prompt" = "true"
WARNING: These git config values clash:
  git config "merge.tool" = "bc3"
  git config "merge.tool" = "vsdiffmerge"
WARNING: These git config values clash:
  git config "mergetool.prompt" = "false"
  git config "mergetool.prompt" = "true"
WARNING: These git config values clash:
  git config "push.default" = "upstream"
  git config "push.default" = "simple"
Git LFS: (0 of 1 files) 0 B / 15.91 MB
Git LFS objects can not be uploaded to this public fork.
Docs: https://github.com/contact
error: failed to push some refs to 'https://github.com/jhessin/Senior_Project.gi                                                                                                                                                    t'
***

The warnings I can deal with (though I would like to fix them if I can), but not being able to push the files is a problem and I have no idea how to fix it.

**Comment by technoweenie** [comment] 2016-04-14 06:40
@jhessin Look into where chocolatey is installing git lfs. Sounds like it's not installing it in your `$PATH`, or you have multiple `git-lfs` commands in your `$PATH` and it's picking the old one.

You can run `git lfs version` to see the current version you have installed, and `which git-lfs` to see exactly which command you're running.

**Comment by jhessin** [comment] 2016-04-14 09:37
@technoweenie Okay now I'm really confused. I ran "git lfs version" in the git BASH and it returns v1.1.2; But when running it inside the git bash launched from GitHub Desktop it says v1.1.0.

Running which git-lfs gives me c/Program Files/Git LFS/git-lfs or ~/AppData/Local/GitHub/lfs-amd64_1.1.0/git-lfs

It looks like it is a permission issue, but I'm not sure how to fix it.

**Comment by shiftkey** [comment] 2016-04-14 10:02
@jhessin GitHub Desktop modifies the PATH inside the shell you've chosen to use a version of `git-lfs.exe` we ship (as well as `git.exe`) so this sounds like the default behaviour.

What happens if you use PowerShell or Command Prompt which has Git installed? (i.e. ignore Git Shell and our version of `git-lfs.exe`)

**Comment by jhessin** [comment] 2016-04-14 12:05
Both command prompts return v1.1.2. When I try to push from them the warnings do not pop up, but the error still shows up.

Does git-lfs require a new repo? Or can it be used with an existing one? This was a preexisting repo - could that be the problem?

**Comment by technoweenie** [comment] 2016-04-14 13:27
Git is designed in a way that discourages changing history. It's possible, but fairly difficult, and will result in different commit shas. Doing a big history change to convert existing large git blobs into lfs pointers will potentially be very disruptive to your dev team.

If you're bringing LFS to an existing project, you have a couple options:

1. You can start using it from today. Just install git lfs, run `git lfs track "*.some-file-ext"`, and start adding new files. The downside is you won't reclaim any space from existing git blobs. Also, this will work much better in v1.2 because of #1104.
2. Use a tool to migrate an existing Git repo. This will be a one time major disruption to your dev flow, unfortunately.
  * The [git lfs migrate tool](https://github.com/bozaro/git-lfs-migrate) was written specifically for LFS, though I haven't tried it.
  * The [BFG repo cleaner](https://github.com/rtyley/bfg-repo-cleaner/releases/tag/v1.12.5) is a great alternative, and one that [GitHub support recommends](https://help.github.com/articles/remove-sensitive-data/). However, it's LFS support has a [nasty bug](https://github.com/rtyley/bfg-repo-cleaner/issues/116).
  * `git filter-branch`, but it's pretty powerful and difficult to use.

**Comment by technoweenie** [comment] 2016-04-14 13:30
> but the error still shows up.

Ah, missed this. I assume you're referring to this:

> Git LFS objects can not be uploaded to this public fork.

This is a behavior on GitHub's LFS server to prevent potential abuse. You can't upload LFS objects to a fork of public repository unless you have push access to the original public repository. I realize this is inconvenient. This is on my roadmap to fix.

**Comment by jhessin** [comment] 2016-04-14 19:53
@technoweenie That would make sense except I DO have push access to the original repository.

I believe this may stem from the fact that the file I am sending already exists and I am only modifying it. I will need to look into the migrate tool you mentioned.

**Comment by technoweenie** [comment] 2016-04-14 20:14
Hmm, can you send me details at https://github.com/contact?

**Comment by fedorov** [comment] 2016-06-01 18:57
My first attempt to give git-lfs a chance - and the same problem. I have never had git-lsf installed on my system before, and git-lfs reports 1.1.2 as the version installed.

Makes me wonder why is this issue closed if users still have this problem?

**Comment by technoweenie** [comment] 2016-06-01 19:01
What values are clashing?  The applied fix only stops non-lfs config values from being reported as clashing.

**Comment by fedorov** [comment] 2016-06-01 19:03
> What values are clashing? The applied fix only stops non-lfs config values from being reported as clashing.

Sorry, I do not understand the question. Here's what I did:

1) install git lfs via brew per instructions
![image](https://cloud.githubusercontent.com/assets/313942/15722111/f9b25c24-2809-11e6-86af-5334c8a55585.png)

2) track large files

3) add those to repo

4) push the repo to my fork (I do have push access to the original repo)

5) observe error
![image](https://cloud.githubusercontent.com/assets/313942/15722100/f07bd356-2809-11e6-886f-4c0f5a5153a6.png)

**Comment by fedorov** [comment] 2016-06-01 19:04
one more detail: I am not modifying existing files, I am adding new files

**Comment by fedorov** [comment] 2016-06-01 19:05
original repo: https://github.com/qiicr/dcmqi; my fork: https://github.com/fedorov/dcmqi

**Comment by technoweenie** [comment] 2016-06-01 19:16
You're having a totally different problem than the one this issue describes. This issue is for the bug that resulted in useless warnings like this:

```
WARNING: These git config values clash:
git config "http.sslcainfo" = "C:/Program Files/Git/mingw64/ssl/certs/ca-bundl e.crt"
git config "http.sslcainfo" = "/ssl/certs/ca-bundle-ghfw.crt"
```

You're not hitting a bug, but your push is being rejected by the server. GitHub doesn't allow new Git LFS objects on public forks unless the pusher a) the pusher has write access to the original or b) the original repo already has Git LFS content.

**Comment by fedorov** [comment] 2016-06-01 19:30
> You're having a totally different problem than the one this issue describes.

Indeed. Sorry about that. I guess I was confused by this comment: https://github.com/github/git-lfs/issues/908#issuecomment-210120857. I am apparently having the same issue as reported by @jhessin.

> You're not hitting a bug, but your push is being rejected by the server. GitHub doesn't allow new Git LFS objects on public forks unless the pusher a) the pusher has write access to the original or b) the original repo already has Git LFS content.

I do have write access to the original. Should I report this as a new issue? Were you able to resolve issue of @jhessin via private follow-up?

**Comment by technoweenie** [comment] 2016-06-01 19:53
> I guess I was confused by this comment

Yeah, that was another separate problem raised in this issue, after it was closed. This confusion is exactly why I like to keep issues focused on a single topic.

I confirmed that you do have access to the original, and the public fork check _should_ be working. Can I see your `git lfs env` output? Also, how are you authenticating with GitHub? Is it possible you're accessing through a different user account?

**Comment by fedorov** [comment] 2016-06-01 20:04
> This confusion is exactly why I like to keep issues focused on a single topic.

Happy to open a new issue if you prefer.

> Can I see your git lfs env output? 

![image](https://cloud.githubusercontent.com/assets/313942/15723827/2d3ab0ca-2812-11e6-9db9-536dd754b807.png)

> Also, how are you authenticating with GitHub?

Hmm. What do you mean? I entered my password once in the terminal, and it is on my keychain now, I am guessing, since I don't need to re-enter it. I can push to this (and other) repositories without problems, when I am not using LFS.

> Is it possible you're accessing through a different user account?

I am not using any other accounts. The original repo belongs to an organization account, not an individual, if this can make any difference.

**Comment by technoweenie** [comment] 2016-06-01 21:38
> Happy to open a new issue if you prefer.

Ha, I think that ship has sailed :)

I pushed a quick update that makes the message more explicit. It now gives your username and the affected repository. While doing this, I saw that the server was sending this same response for anonymous requests too. That bug should be fixed. What message do you see now?

**Comment by fedorov** [comment] 2016-06-02 00:02
👍  it "just works" now - thanks! 👍

**Comment by technoweenie** [comment] 2016-06-02 14:21
Of course it does, lol. `/khanify computers`. Glad you got it working! Please open a new issue if you have other problems :)

**Comment by fedorov** [comment] 2016-06-02 14:30
Thanks a lot for your help! Impressed with the prompt response.
