### ISSUE TITLE
Feedback on pointer file spec

### ISSUE THREAD

**Issue by swisspol** [github/git-lfs#233] opened 2015-04-15 02:07 UTC
1) It doesn’t indicate if the pointer file contents is case-sensitive or not: I think it should *not* be, to follow established patterns with Git config files and CLI arguments which are only case-sensitive where it makes sense

2) Saying "The pointer file should be small (less than 200 bytes), and consist of only ASCII characters” doesn’t appear to add anything since it’s impossible not to comply considering the pointer file format, so it’s adding confusion IMO (implying this that something that cannot happen could happen)

3) "Libraries that generate this should write the file identically”: should -> MUST

4) The sample has "(ending \n)” at the end but the spec doesn’t say if required or not, so is it or not? IMO it should be, so each line is clearly `{key} {value}\n`

5) "Use properties "version", "oid", and "size" in that order.” seems a really bad idea for what is clearly a list of key-value pairs without any meaningful ordering: it’s adding constraints which are guaranteed to create issues in the future if/when new keys are added / deprecated / made optional

6) It doesn’t address how clients could add private key-value pairs to this file - related to 5

7) I think the version field should be like `1:https://git-lfs.github.com/spec/v1` as this makes parsing trivial (version = what’s before the column) and it avoids any ambiguity comparing URLs e.g. what if someone put in there `http://git-lfs.github.com/spec/v1`? Should you fail? pass? What kind of fuzzy logic is needed?

8) Considering the pointer files are clearly structured data vs just a list of one SHA1 per line for instance, I’m curious as to why the decision was made to create a new file format vs using the Git config one which is well known, extensible, and people have parser for (YAML or JSON would be nice, but they’re not used anywhere in Git).

**Comment by technoweenie** [comment] 2015-04-15 03:19
Thanks for the feedback.  I'll try to address each point:

1. I want different Git LFS implementations to generate the exact same pointer file, such that it hashes to the same Git blob oid.  IMO pointers should be case sensitive (and the spec should make this clear).
2. Sure, good point.  
3. :+1:
4. I think the spec should make it clear that the line break is required.
5. The order has to be consistent so that different Git LFS implementations generate the same file, which leads to the same Git blob OID.
6. They probably shouldn't, otherwise Git LFS may rewrite the blob and clobber unknown values.  I've had some ideas on other possible key/value pairs though, and am open to the idea.  Would be interested to hear specific use cases though.
7. IMO the version url shouldn't change, unless you're using a different, incompatible version.  Inspired by [xml namespaces](http://en.wikipedia.org/wiki/XML_namespace).  Four words I never thought I'd type :)
8. I designed them to look like the non-blob objects stored in git: `key SP value`.

        $ git cat-file -p `git rev-parse master`
        tree 776003038ef7b60bdfed6d3d645ab66d6b160dd8
        parent 1cb54bcdf1624ef43ba6bd2f89ad4f066277144e
        parent 05d4692e9fddefba46fe8ab275afe86574904233
        author risk danger olson <technoweenie@gmail.com> 1428694427 +0200
        committer risk danger olson <technoweenie@gmail.com> 1428694427 +0200

**Comment by swisspol** [comment] 2015-04-15 04:28
> Would be interested to hear specific use cases though.

Well since GitHub is the standard for Git hosting *and* large files are a big problem with Git *and* I can imaging the ecosystem of Git tools adopting this extension *and* later down the road have asset management tools be created around it, it makes complete sense to expect people to want to attach some extra metadata in there (of course you don't wanna design the spec to say allow embedding an entire EXIF payload but there's a middle ground for simple key-value pairs).

The burden of proof is the other way around - can you make a case beyond reasonable doubt that metadata will never be needed or that the cost of supporting it clearly outweights its benefit? ;) Because the alternative to retrieve a 100 bytes of metadata is a round-trip to the server to download a multi-megabytes asset.

> The order has to be consistent so that different Git LFS implementations generate the same file, which leads to the same Git blob OID.

That's a laudable goal, but it seems very hard to enforce (the spec doesn't even mention that today nor comes with a sample code to validate the expected OIDs), it prevents extensibility, but more importantly, why would it matter?

I mean are different Git backends *required* to generate the exact same SHA1s when creating a commit with the same *user-level* provided input data otherwise things would break? I cannot imagine why this would even be a problem the way Git works today but I might be missing something.

IMHO the big problem with this requirement is that it's not enforced. When server APIs require signing with HMAC for instance, the server verify that the payloads signature matches, and reject the call if not. So that's consistent: the spec says you MUST structure your payload only in one way then sign it, otherwise things will not work. And they don't.

In this case here, will GitHub servers extract the fields from the file pointer, regenerate it and recompute the OID from it, compare and reject when pushing to a repo commits with file pointers? That's very complex and even GitHub does it, I cannot imagine all Git hosting services doing. So here comes contamination... This means consistent OIDs is just an arbitrary rule that cannot be enforced, and by definition, nobody can make any assumption about it, which is equivalent to not having it.

**Comment by swisspol** [comment] 2015-04-15 04:31
> I mean are different Git backends required to generate the exact same SHA1s when creating a commit with the same user-level provided input data otherwise things would break?

One thing I can think of is that not all Git implementation might use sub-second resolution timestamps when creating commits.

**Comment by swisspol** [comment] 2015-04-15 04:37
> IMO the version url shouldn't change, unless you're using a different, incompatible version.

Agreed, but my point was about comparing to determine if they have "changed": is `http://git-lfs.github.com/spec/v1` equal to `https://git-lfs.github.com/spec/v1`?

If you want to use URLs for versioning vs a simple integer field, then the spec must explain how to compare them. It's a whole section of the XML spec: http://www.w3.org/TR/REC-xml-names/#NSNameComparison.

**Comment by swisspol** [comment] 2015-04-15 04:39
Side note: it's really great to see GitHub driving a concrete effort for large files support in Git :+1:

I'm only pointing all these things because, considering the weight GitHub carries when it comes to Git, I *really* believe the spec should be super tight. The last thing we need is ambiguities which turn into different interpretations by different Git tools or Git hosting companies.

**Comment by technoweenie** [comment] 2015-04-15 12:32
> it makes complete sense to expect people to want to attach some extra metadata in there (of course you don't wanna design the spec to, say, allow embedding an entire EXIF payload, but there's a middle ground for simple key-value pairs).

The Git LFS pointer file is specifically to tell the client enough information to download the file effectively on checkout.  Optional meta data can be added in other ways.  I'm open to re-evaluating if there's a really great use case, though.  

> That's a laudable goal, but it seems very hard to enforce (the spec doesn't even mention that today nor comes with a sample code to validate the expected OIDs), it prevents extensibility, but more importantly, why would it matter?

It matters because the clean filter will mark the file as updated if the generated pointer file is different.  If the spec can stay small and strict, then I don't see it as a problem.

> If you want to use URLs for versioning vs a simple integer field, then the spec must explain how to compare them.

If I'm reading that spec correctly, then it's saying to use simple string comparison, and not any kind of url resolution or matching.  That sounds good.

> I really believe the spec should be super tight. The last thing we need is ambiguities which turn into different interpretations by different Git tools or Git hosting companies.

Definitely.  Thanks for your feedback.  I'm all for tightening the spec up, and will ping you on a PR to address some of your points here.

**Comment by swisspol** [comment] 2015-04-15 15:48
> I'm open to re-evaluating if there's a really great use case, though.

The problem is the way the spec is currently designed, it's so inflexible that it pretty much guarantees you can't add new key-value pairs without breaking things in practice. Which means when the time comes (I'd bet on "when" not "if"), the version will have to be revised which means you will have an ecosystem of tools supporting v1 but not v2 (and breaking the pointer files that go through it) or the other way around.

> It matters because the clean filter will mark the file as updated if the generated pointer file is different.

That is a very good point because it gives a very good reason for the ecosystem of tools to comply.

Here's my suggestion at a high-level revised pointer-file spec to attempt to unifying things while leaving the door open for future extensions:

================

- Pointer files are text files which MUST contain only UTF-8 characters (this ensures international support for the future)
- Each line MUST be of the format `{key} {value}\n` (unix newline, not windows or whatever)
- Only a single space character between `{key}` and `{value}`
- Keys MUST be using ASCII characters only
- Keys MUST be lowercase
- Keys MUST NOT contain whitespaces
- Lines of key-value pairs MUST be sorted alphabetically in ascending order (this ensures both OID stability AND extensibility of key-value pairs)
- Values may contain whitespaces
- Custom or third-party key-value pairs MUST have their keys use reverse-DNS notation e.g. `com.gitup.my-key` - plain (i.e. non-reverse DNS) keys are reserved EXCLUSIVELY for use by the spec
- Pointer files SHOULD not have the executable bit set when checked-in in Git

Required key-value pairs for v1:
 - (list goes here)

Example v1 pointer file:
(goes here)

For testing compliance of any tool generating its own pointer files, the reference is the official GitHub tool: - Run it with the command `(fill in)` to generate a pointer file for the passed-in large file
- Run your own tool and generate your own pointer file
- Run the Git command `(fill in)` and compare that the generate OIDs between the official GitHub tool and yours is the same

For tools that parse and regenerate pointer files, they MUST preserve (i.e. copy as-is) keys they don't know or care about.

Note that because of the way pointer files are used by Git, their contents is in-effect case-sensitive.

=============

This should address both your requirements and the potential issues I was pointing out :)

> If I'm reading that spec correctly, then it's saying to use simple string comparison, and not any kind of url resolution or matching. That sounds good.

Indeed and it goes out of its way to say that *equivalent* URLs are not *equal*, which IMO is very important.

**Comment by swisspol** [comment] 2015-04-15 15:50
The alphabetical sorting is inspired from http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html which works great.

**Comment by swisspol** [comment] 2015-04-15 15:56
I moved the my suggested revised spec to a Gist since I kept modifying it - should be good now though :)

https://gist.github.com/swisspol/b9856fcca81029efb960

**Comment by technoweenie** [comment] 2015-04-15 16:14
> I moved the my suggested revised spec to a Gist since I kept modifying it

Looks good :+1:

> Custom or third-party key-value pairs MUST have their keys use reverse-DNS notation e.g. com.gitup.my-key - plain (i.e. non-reverse DNS) keys are reserved EXCLUSIVELY for use by the spec

I'd rather replace this with a note that custom keys are not supported.  While your revised spec makes adding them to the pointer file spec possible without introducing a new version, we still haven't figured out how `git-lfs` should handle properties it doesn't know about in the code.

I do like  the idea of `version` being first always.  Any thoughts on making that an exclusion?

```
version someurl
abc def
oid {oid}
size 123
zyx wvu
```

This should make it easy for parsers to quickly figure out what version they're dealing with, while continuing to support possible key additions.  This also doesn't change existing pointer files.

**Comment by swisspol** [comment] 2015-04-15 16:32
> I'd rather replace this with a note that custom keys are not supported. While your revised spec makes adding them to the pointer file spec possible without introducing a new version, we still haven't figured out how git-lfs should handle properties it doesn't know about in the code.

What's there's to handle? Is there more to just keeping them around in a dict then writing them back? What am I missing?

Seems like a very short-term limitation you will have to solve anyway, so it should really not bear on the spec IMO. The last thing you want is some sort of post 1.0 release of the GitHub tool not being able to handle this correctly :)

> I do like the idea of version being first always. Any thoughts on making that an exclusion?

Why? What's the *engineering* rationale for this?

I'll even go one step further: you will actually notice that with my proposed spec'ed, since it's forward/backward compatible, there's actually no need for a version in the first place: it's implied.

Think about it, what matters is the presence of keys: parse pointer files, extract the 4 required keys you need, if they're here good, if not fail with error message. Compare with extracting version, comparing version, build logic to handle combination of versions and missing / present keys, degenerated cases if a version is the right one, but some keys are still missing, etc...

The question therefore becomes: what's the use case for a version field? What breaks in the toolchains or large file ecosystem if there's none?

If you really want a version field, I think it's a pretty bad idea to have this key looks like any other key and have the rule not apply to it - quite confusing. Instead, consider a special character prefix and format e.g. `#version=foobar\n` which comes with a rule that the first line MUST be this special thing. An example that comes to mind is the `<!DOCTYPE html>` at the beginning of HTML docs which is different than regular tags.

XML has a namespace/version because the same format is used for a variety of contents so you need to know what contents is in there. This doesn't apply here since it's a file format for one and only one goal.

**Comment by swisspol** [comment] 2015-04-15 16:34
I tweaked the spec a bit: https://gist.github.com/swisspol/b9856fcca81029efb960/revisions

**Comment by swisspol** [comment] 2015-04-15 16:39
One question pending for me is how should newline and returns characters be escaped? They can't be in the values as the spec says for obvious reasons, but it would nice (although not *required*) to allow it.

**Comment by technoweenie** [comment] 2015-04-15 16:47
> What's there's to handle? Is there more to just keeping them around in a dict then writing them back? What am I missing?

The fact that between Git Media and the tools it has inspired don't have any thing in their pointer other than oid leads me to believe this isn't a problem.  If someone wants to solve it in code, that's great.  I don't want the spec to promote something that hasn't been implemented in the code, or even fully thought through.  Luckily, your revised spec makes it easy to support new keys in the pointer format.  We can edit markdown and code easily.

> I do like the idea of version being first always. Any thoughts on making that an exclusion?
>> Why? What's the engineering rationale for this?

Those are all good points, but not good enough to change the spec at this point IMO.  If we get to a point where we have to make a major version bump, we can revisit how or even if the version is specified.  I wouldn't mind `# version {url}` or even just `# {url}` at the top.

> One question pending for me is how should newline and returns characters be escaped? They can't be in the values as the spec says for obvious reasons, but it would nice (although not required) to allow it.

The white list of allowed characters in point 4 of your revised spec leaves these out. :+1:

**Comment by swisspol** [comment] 2015-04-15 16:56
> The fact that between Git Media and the tools it has inspired don't have any thing in their pointer other than oid leads me to believe this isn't a problem.

I'm confused, what is "this" referring to in this sentence?

> Those are all good points, but not good enough to change the spec at this point IMO.

Just to be clear, you're saying you want a version field, but you're OK with not having it use the standard key format so it doesn't create any confusion, right?

> If we get to a point where we have to make a major version bump, we can revisit how or even if the version is specified. I wouldn't mind # version {url} or even just # {url} at the top.

If there's one that actually needs to be rock stable forever that's how the version itself is specified ;)

**Comment by technoweenie** [comment] 2015-04-15 17:13
>> The fact that between Git Media and the tools it has inspired don't have any thing in their pointer other than oid leads me to believe this isn't a problem.

>I'm confused, what is "this" referring to in this sentence?

The problem of not supporting custom keys in the pointer spec.  

> Just to be clear, you're saying you want a version field, but you're OK with not having it use the standard key format so it doesn't create any confusion, right?

Sure.  I don't have any interest in changing the current pointer spec _just_ to change it though.

**Comment by swisspol** [comment] 2015-04-15 17:15
> I don't have any interest in changing the current pointer spec just to change it though.

Wouldn't it be part of the other changes like alphabetical sorting of keys?

**Comment by technoweenie** [comment] 2015-04-15 17:20
> Wouldn't it be part of the other changes like alphabetical sorting of keys?

I'm keeping the version at the top so that existing Git LFS objects are still compliant with the revised spec.

**Comment by technoweenie** [comment] 2015-04-15 17:44
Regarding the commands you suggested:

> Run it with the command (fill in) to generate a pointer file for the passed-in large file

How about something like:

    $ git lfs pointer path/to/large-file
    version https://git-lfs....
    oid ...
    size ...

> Run the Git command (fill in) and compare that the generate OIDs between the official GitHub tool and yours is the same

I'm not sure what the point here is.  Can't you just look at the two pointers?  Though if we had a command:

    $ cat some/other/pointer | git lfs pointer path/to/large-file
    # either return exit 0, or non zero and a diff?
    - version https://git-lfs....
    + # https://git-lfs....

How do you envision these commands working?

**Comment by swisspol** [comment] 2015-04-15 17:50
> I'm keeping the version at the top so that existing Git LFS objects are still compliant with the revised spec.

Ah, lucky that the alphabetical order doesn't change the current file pointers!

> Can't you just look at the two pointers? Though if we had a command:

If the requirement is that OIDs for file pointers match, then the compliance must be verified by comparing OIDs generated by Git for the blobs, not diffing text visually.

Maybe using something like (see http://git-scm.com/book/en/v2/Git-Internals-Git-Objects):
```
$ echo 'test content' | git hash-object -w --stdin
d670460b4b4aece5915caf5c68d12f560a9fe3e4
````

**Comment by technoweenie** [comment] 2015-04-15 17:54
> Ah, lucky that the alphabetical order doesn't change the current file pointers!

Ha, yes :)

> If the requirement is that OIDs for file pointers match, then the compliance must be verified by comparing OIDs generated by Git for the blobs, not diffing text visually.

Even better.  :+1:

**Comment by MarkusTeufelberger** [comment] 2015-04-16 19:25
Maybe also check out https://github.com/github/git-lfs/issues/229 as a potential alternative for a pointer file spec... While there might be more overhead due to XML and a more rich file format, it is still negligible compared to what these files should point to. The advantage would be that Metalink is designed to be exactly what these pointer files try to do: A collection of file information (e.g. hash, name, size...), and location(s) where to find the file contents (HTTP mirrors, BitTorrent info hashes, FTP servers...).

The current spec seems to assume only a single location for file contents which might be useful for large service providers like GitHub, but does not in my opinion make this feature very flexible or adaptable. What about the use case for example to offer an internal asset server or load files mainly from an AmazonS3 bucket - but if something fails, use the quota at GitHub?

**Comment by swisspol** [comment] 2015-04-16 20:16
> While there might be more overhead due to XML and a more rich file format, it is still negligible compared to what these files should point to.

XML is overkilled for this. It sounds simple on the surface, but it's a really complex file format with lots of special cases. It would require everyone to use parsing libraries and then walk the XML tree and everything. Lots of overhead and error handling just to get the idea.

> What about the use case for example to offer an internal asset server or load files mainly from an AmazonS3 bucket - but if something fails, use the quota at GitHub?

No matter what this implies a custom tool anyway since the GitHub one won't handle this, so if you have a custom tool, you can have your own incompatible format.

Or you can just set up a proxy server.

**Comment by swisspol** [comment] 2015-04-16 20:22
> I'm keeping the version at the top so that existing Git LFS objects are still compliant with the revised spec.

I thought more about this, and I really with this could be reconsidered. The spec is pre-1.0 and barely used today. Once things ramp up it will be around for 10 years and used by thousands of people and hundred of thousands of files minimum. Having a pointer file format with some avoidable clunkiness will generate some real costs and frustration down the road.

Custom key-value pairs should be supported from day 1 by the official tool and the version field should become something like `<!DOCTYPE html>` for HTML.

The cost of changing the spec right now to be more future proof is negligible in the grand scheme of things.

**Comment by technoweenie** [comment] 2015-04-17 16:00
>> The current spec seems to assume only a single location for file contents which might be useful for large service providers like GitHub, but does not in my opinion make this feature very flexible or adaptable. What about the use case for example to offer an internal asset server or load files mainly from an AmazonS3 bucket - but if something fails, use the quota at GitHub?
> Or you can just set up a proxy server which can handle such situations transparently.

This is one of the goals of Git LFS: push as much of the configuration to the servers.  It's a simple HTTPS spec that we hope will be implemented by other Git servers.  You can also push your large files to alternate Git LFS servers outside of your Git host.  Maybe you want a small server in the cloud that directs files to your own S3 bucket?  Or maybe you want to set up a local proxy/cdn server so that an entire office of coworkers only needs to download the content once from the remote source.  There's a lot of flexibility with HTTPS APIs.

> The cost of changing the spec right now to be more future proof is negligible in the grand scheme of things.

I'm open to changing the spec before v1.0.  I'd prefer to do it just once if possible.  So, let me know if you have a compelling use case for custom keys that Git LFS _needs_ in the pointer to effectively download the file.  Also, an alphabetical list of keywords does allow custom keys.  We don't need to break the pointer format.

**Comment by swisspol** [comment] 2015-04-17 17:05
> It's a simple HTTPS spec that we hope will be implemented by other Git servers.

It does have 4 HTTP redirect codes which doesn't seem that simple ;)

>  So, let me know if you have a compelling use case for custom keys that Git LFS needs in the pointer to effectively download the file.

That's only 1 use case, the primary one I was thinking about and mentioning above is caching metadata for the large file in the file pointer. Furthermore, if the custom keys affect the file download, then the spec is not really interoperable. Custom keys should be used for metadata, orthogonal to the actual download IMO. That's the beauty of it.

It's very inefficient to download a 1 GB file to retrieve a 100 bytes of metadata or having to store it in a sidecar file while you already have a file pointer that could store the metadata for immediate access.

It could be used for something as simple as tags, or the name of the tool that generated the 

> Also, an alphabetical list of keywords does allow custom keys. We don't need to break the pointer format.

Except for the `version` field.

**Comment by natbro** [comment] 2015-04-20 13:26
Great thread. I agree XML is overkill - wondering if YAML might be considered? it seems to me pretty crazy to re-invent a key/value file format spec and have people do possibly broken or non-compliant parsing when YAML has many very tight, small, and correct parsers out there. the current file is in fact /almost/ correct YAML if the key/value pairs had ':''s between them afaict.

**Comment by technoweenie** [comment] 2015-04-20 15:07
YAML and TOML were considered.  The pointer format was designed to look like the format Git uses to store commit/tree/tag objects.

**Comment by natbro** [comment] 2015-04-20 20:08
i'm not enough of a GIT-head to know how often extensions interact with the commit/tree/tag objects (I only know I have never interacted with them). I guess this file-type seems more common and perhaps in people's face in their tools, or something that lots more custom tools will work with, so that might influence the format a bit more. nutshell: the extensibility/fragility leaves a bit to be desired, which is why YAML seems like it would make good sense.

**Comment by technoweenie** [comment] 2015-04-24 20:32
Thanks for the feedback, everyone!  #246 landed, with an enhanced spec, and a `pointer` tool to help build and compare pointer files.

**Closed by technoweenie** 2015-04-24 20:32 UTC
