### ISSUE TITLE
confusing no usage text found each command

### ISSUE THREAD

**Issue by Aorjoa** [github/git-lfs#672] opened 2015-09-18 03:43 UTC
When run alias commands but not same expected output and some time have  `Sorry, no usage text found for "git-lfs"` in tail of output, I would like to show as below.

same version are running (a62e510ff)
```
$ git lfs version
git-lfs/0.6.0 (GitHub; darwin amd64; go devel +62f169c Thu Jun 18 05:31:38 2015 +0000)
$ git-lfs version
git-lfs/0.6.0 (GitHub; darwin amd64; go devel +62f169c Thu Jun 18 05:31:38 2015 +0000)
```
show help
```
$ git lfs --help
No manual entry for git-lfs
$ git lfs -h
Git LFS provides large file storage to Git.
Sorry, no usage text found for "git-lfs"`
but
$ git-lfs --help
Git LFS provides large file storage to Git.
Sorry, no usage text found for "git-lfs"
$ git-lfs -h
Git LFS provides large file storage to Git. 
Sorry, no usage text found for "git-lfs"
```
and no one show help.

**Comment by sinbad** [comment] 2015-09-18 09:20
The help text is extracted from the man pages with `go generate`, the easiest way to make this happen is to run `script/integration` at least once since #665 was merged, or you can do it manually with `go generate ./commands`. Builds after that will have help text.

**Comment by Aorjoa** [comment] 2015-09-18 11:36
After run script `script/integration` and result that

```
$ git lfs -h
Git LFS provides large file storage to Git.
git lfs <command> [<args>]
..... (Normal) .....
$ git lfs --help
No manual entry for git-lfs
$ git-lfs --help
Git LFS provides large file storage to Git.
git lfs <command> [<args>]
..... (Normal) .....
```

**Comment by sinbad** [comment] 2015-09-18 14:03
Unfortunately git intercepts `git lfs --help`, we never get to see it. You need to use `git lfs help` or `git-lfs --help`. When man pages are actually installed it might work though.

**Comment by Aorjoa** [comment] 2015-09-18 16:00
Thanks @sinbad :)

**Comment by wjdp** [comment] 2015-10-03 17:45
I'm running 1.0 on Ubuntu 15.04 and getting no help text:

```
$ git-lfs --help
Sorry, no usage text found for "git-lfs"
$ git lfs help                              
Sorry, no usage text found for "git-lfs"


```

**Comment by martingkelly** [comment] 2015-10-07 16:45
I'm also having this issue, with version 1.0.0 of the Debian package. It seems like the generated manpages are empty as well.

$ git lfs help
Sorry, no usage text found for "git-lfs"

$ dpkg -l git-lfs
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                    Version                  Architecture             Description
+++-=======================================-========================-========================-===================================================================================
ii  git-lfs                                 1.0.0                    amd64                    Git Large File Support

$ dpkg -L git-lfs
/.
/usr
/usr/share
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/git-lfs-ext.1.gz
/usr/share/man/man1/git-lfs-pre-push.1.gz
/usr/share/man/man1/git-lfs-push.1.gz
/usr/share/man/man1/git-lfs-env.1.gz
/usr/share/man/man1/git-lfs-logs.1.gz
/usr/share/man/man1/git-lfs-fsck.1.gz
/usr/share/man/man1/git-lfs-init.1.gz
/usr/share/man/man1/git-lfs-uninit.1.gz
/usr/share/man/man1/git-lfs-pointer.1.gz
/usr/share/man/man1/git-lfs-status.1.gz
/usr/share/man/man1/git-lfs-pull.1.gz
/usr/share/man/man1/git-lfs-update.1.gz
/usr/share/man/man1/git-lfs-ls-files.1.gz
/usr/share/man/man1/git-lfs-fetch.1.gz
/usr/share/man/man1/git-lfs-checkout.1.gz
/usr/share/man/man1/git-lfs-track.1.gz
/usr/share/man/man1/git-lfs.1.gz
/usr/share/man/man1/git-lfs-untrack.1.gz
/usr/share/man/man1/git-lfs-smudge.1.gz
/usr/share/man/man1/git-lfs-clean.1.gz
/usr/share/doc
/usr/share/doc/git-lfs
/usr/share/doc/git-lfs/changelog.gz
/usr/share/doc/git-lfs/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/git-lfs
/usr/bin
/usr/bin/git-lfs

$ ls -l /usr/share/man/man1/git-lfs*
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-checkout.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-clean.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-env.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-ext.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-fetch.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-fsck.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-init.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-logs.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-ls-files.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-pointer.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-pre-push.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-pull.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-push.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-smudge.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-status.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-track.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-uninit.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-untrack.1.gz
-rw-r--r-- 1 root root 20 Sep 30 22:35 /usr/share/man/man1/git-lfs-update.1.gz

**Comment by martingkelly** [comment] 2015-11-24 18:46
The issue is still present in git-lfs version 1.1.0.

**Comment by arghdos** [comment] 2015-12-15 15:46
Same issues on 14.04 with git-lfs version 1.1.0 installed via the bash script / package repo

**Comment by deivid-rodriguez** [comment] 2016-02-10 19:01
Same issue here with 1.1.1
```
$ git lfs
git-lfs/1.1.1 (GitHub; linux amd64; go 1.5.3)
Sorry, no usage text found for "git-lfs"
```

**Comment by technoweenie** [comment] 2016-08-18 16:00
We've improved this greatly in recent months. Man pages should be installed properly when using our RPM and Deb packages. Otherwise, you can run commands like:

```bash
$ git lfs help
$ git lfs help <subcommand>
```

**Closed by technoweenie** 2016-08-18 16:00 UTC

**Comment by pronobis** [comment] 2017-03-07 06:54
I just installed a deb package with the bash script on Ubuntu 16.04 and:
`git lfs help`
gives 
`Sorry, no usage text found for "git-lfs"`

**Comment by ttaylorr** [comment] 2017-03-07 16:03
@pronobis could you please open a new issue instead?

**Comment by antgel** [comment] 2018-10-13 11:50
@technoweenie It's still an issues with Ubuntu 18.04.

**Comment by ttaylorr** [comment] 2018-10-15 14:15
@antgel sorry that you're having trouble. Can you please open a new
issue instead? We discourage users from commenting on already-closed
issues, as it creates notification noise for the original author (whose
issue may have already been fixed).

We would be more than happy to help you out there, and figure out what's
going on. In addition, @technoweenie no longer works on this project
actively, so please mention @git-lfs/core, instead.
