### ISSUE TITLE
git lfs ls-files not returning files after tracking them

### ISSUE THREAD

**Issue by shammellee** [github/git-lfs#700] opened 2015-10-04 17:05 UTC
I ran the following…
```bash
$ git lfs init
$ git lfs track "src/img"
$ git add src/img
$ git lfs track
Listing tracked paths
    src/img (.gitattributes)
$ git lfs ls-files
```
and it returned nothing

**Comment by kankaristo** [comment] 2015-10-04 20:08
It requires you to commit them, before the files are actually tracked.

It would be nice if `git lfs ls-files` listed staged files as well (maybe unstaged as well, similar to how `git status` does).

**Comment by rubyist** [comment] 2015-10-04 20:15
`git lfs status` should show the staged files.

**Comment by shammellee** [comment] 2015-10-04 20:21
@kankaristo wouldn't that defeat the purpose of `lfs` by making the repo size larger?

**Comment by kankaristo** [comment] 2015-10-04 20:50
@shammellee, no, LFS "intercepts" the files when you commit them. Your workflow is exactly the same as it is without Git LFS, you just tell it which files it should handle (when committing) by tracking them. As far as I've understood anyway, I just started using it today.

@rubyist, thanks, I didn't actually know about `git lfs status`.

**Comment by shammellee** [comment] 2015-10-04 20:52
Oh yea, forgot about that part!

Thanks

**Comment by KingScooty** [comment] 2015-10-24 12:05
I think this is still an issue :/

```
$ git lfs init
$ git lfs track "*.psd"
$ git add .
$ git commit
$ git push
$ git lfs ls-files
```

Returns blank. 

```
$ git lfs track
```

Returns this:

```
Listing tracked paths
    *.psd (.gitattributes)
```

**Comment by KingScooty** [comment] 2015-10-24 12:23
Weirdly, if i also track the folder the PSDs are in, it works fine.

**Comment by technoweenie** [comment] 2015-10-26 14:35
What do all of your repository's `.gitattributes` files look like? The `git lfs track` command only shows those with `filter=lfs`, but it's possible for other filters to interfere with Git LFS.

**Comment by ysolovyov** [comment] 2016-08-08 09:08
guys, i have opencv2.framework in my project. Its not tracked by lfs, i want to update it and use lfs cause new framework is > 100mb size. I call:

git lfs track "opencv2.framework"
Tracking opencv2.framework

.gitattributes becomes
opencv2.framework filter=lfs diff=lfs merge=lfs -text

then update this framework and call:

git add opencv2.framework/

git lfs status
On branch master
Git LFS objects to be pushed to origin/master:

Git LFS objects to be committed:

Git LFS objects not staged for commit:

So everything is empty.

git lfs ls-files
empty also

What is going on?

git lfs version
git-lfs/1.2.0 (GitHub; darwin amd64; go 1.6.1)

**Comment by technoweenie** [comment] 2016-08-08 14:37
Git's `.gitattributes` file doesn't work on directories. Try `git lfs track "opencv2.framework/**/*"`.

**Closed** 2016-08-18 15:57 UTC

**Comment by MSR-Redmond** [comment] 2016-08-23 01:26
This still isn't working for me, what's the trick?

**Comment by gessulat** [comment] 2016-08-30 09:39
I am having the same issue, when following this tutorial:

https://github.com/github/git-lfs/wiki/Tutorial

at the `git lfs ls-files` step, nothing is returned. I am trying this on a MacOS X 10.11.6.

**Comment by technoweenie** [comment] 2016-08-30 15:06
@gessulat That's because the tutorial has you run `git add` on the `*.bin` files before running `git lfs track`. The track command doesn't apply retroactively to files, and the tutorial mentions using BFG to update existing files.

**Comment by cepages** [comment] 2016-09-15 11:13
I think this steps are clearer: https://git-lfs.github.com/

**Comment by b0r1sp** [comment] 2017-12-23 12:41
update:

`$ git init
$ git lfs install
$ git lfs track "*.psd"
$ git add -A
$ git commit -m "add files"
$ git lfs ls-files`

**Comment by stemangiola** [comment] 2018-02-14 22:57
Hello,

I followed the instructions here https://git-lfs.github.com/

and still get nothing with 

git lfs ls-files

I am using 

git version 2.7.2
git-lfs/2.3.4 (GitHub; linux amd64; go 1.9.1; git d2f6752f)

**Comment by ttaylorr** [comment] 2018-02-15 20:55
Hi @shammellee, thanks for commenting here. It looks like your Git version is a little out of date; can you upgrade to the latest release and try again? One caveat which sometimes is tricky is that Git LFS will _not_ list empty files, since empty files are not considered LFS objects by the specification.

Let me know if neither of those were it, and I'd be happy to reopen this.

**Comment by flynn16** [comment] 2018-05-14 18:41
Maybe the globbing wasn't quite right. Try this:

```
git lfs track 'src/img/**'
```

**Comment by mstuart1** [comment] 2019-03-21 17:29
I am also having this problem. 

I have a file that is ~200MB, for this example called test.csv.

`git lfs track "test.csv"`
`git lfs track` returns

Listing tracked patterns
   test.csv (.gitattributes)
Listing excluded patterns

`git lfs ls-files` 
returns nothing.

I added, still git lfs ls-files returned nothing.
I committed, still ls-files returned nothing.
I pushed.  Pushed failed and suggest I try using LFS.

**Comment by jasperboyd** [comment] 2020-01-23 19:47
Having the same issue as @mstuart1 

Tried to push to github got:

```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: da097d2ebbfaa13bbd67198c8c2e512b
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File path/to/aws-java-sdk-1.11.712.jar is 148.90 MB; this exceeds GitHub's file size limit of 100.00 MB
```

Installed git lfs extension and on the repo

```
git lfs track "*.jar"
git add .gitattributes
git commit -m "committing"
```

jars now show as dirty so recommitted all in bulk, when attempting to push to origin same error 

```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: da097d2ebbfaa13bbd67198c8c2e512b
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File path/to/aws-java-sdk-1.11.712.jar is 148.90 MB; this exceeds GitHub's file size limit of 100.00 MB
```

Also attempted a 

```
git rm --cached integrationServices/davisdigital/aws-java-sdk-1.11.712.jar
git commit -m "removing"
```

and then recommitted

`git lfs ls-files` includes the problematic jar but I can't push to origin (github)

**Comment by bk2204** [comment] 2020-01-23 20:34
Hey,

This is a little bit of a different issue.  The problem is that you have large objects in your history and need to migrate the history of your project to turn those into LFS objects.  You'll want to look at the documentation for `git lfs migrate`.  Since this is a different issue, if you still have trouble, please open a new issue, and we'll help you there.

**Comment by jasperboyd** [comment] 2020-01-23 20:49
Hey @bk2204 Thanks for the quick response I had a feeling the issue had to do with it existing at some point in the git history I'll take a look at the docs. Cheers!

**Comment by rolltidehero** [comment] 2020-07-10 18:47
> I think this is still an issue :/
> 
> ```
> $ git lfs init
> $ git lfs track "*.psd"
> $ git add .
> $ git commit
> $ git push
> $ git lfs ls-files
> ```
> 
> Returns blank.
> 
> ```
> $ git lfs track
> ```
> 
> Returns this:
> 
> ```
> Listing tracked paths
>     *.psd (.gitattributes)
> ```

**This method worked for me. My issue was that my .gitattributes was messed up. Here is my .gitattributes from the successful LFS commit.**

`*.7z filter=lfs diff=lfs merge=lfs -text
*.mdf filter=lfs diff=lfs merge=lfs -text
*.ndf filter=lfs diff=lfs merge=lfs -text
*.ldf filter=lfs diff=lfs merge=lfs -text`

**I also had to remove those same extensions from my .gitignore file.**
